version: "3.9"

services:
  redis:
    image: redis:7
    container_name: currency-redis
    ports:
      - "6379:6379"

  currency-service:
    build: .
    container_name: currency-service
    ports:
      - "50051:50051"
    environment:
      - API_KEY=${API_KEY} 
      - REDIS_ADDR=redis:6379
      - GRPC_ADDR=:50051
    depends_on:
      - redis
